"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 800

format = """
[](surface0)\
$os\
$directory\
[](fg:surface0 bg:surface1)\
$git_branch\
$git_status\
[](fg:surface1 bg:surface2)\
$nodejs\
$bun\
$java\
$dart\
[](fg:surface2 bg:overlay0)\
$docker_context\
$kubernetes\
$aws\
$gcloud\
[](fg:overlay0)\
$fill\
$cmd_duration\
$line_break\
$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo  = "#f2cdcd"
pink      = "#f5c2e7"
mauve     = "#cba6f7"
red       = "#f38ba8"
maroon    = "#eba0ac"
peach     = "#fab387"
yellow    = "#f9e2af"
green     = "#a6e3a1"
teal      = "#94e2d5"
sky       = "#89dceb"
sapphire  = "#74c7ec"
blue      = "#89b4fa"
lavender  = "#b4befe"
text      = "#cdd6f4"
subtext1  = "#bac2de"
overlay0  = "#6c7086"
surface2  = "#585b70"
surface1  = "#45475a"
surface0  = "#313244"
base      = "#1e1e2e"
crust     = "#11111b"

[os]
disabled = false
style = "bg:surface0 fg:text"
[os.symbols]
Macos = " "

[directory]
style = "bg:surface0 fg:blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Developer" = "󰲋 "
"dev" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:surface1"
format = '[ $symbol $branch ](fg:peach bg:surface1)'

[git_status]
style = "bg:surface1"
format = '[$all_status$ahead_behind ](fg:red bg:surface1)'

[nodejs]
symbol = ""
style = "bg:surface2"
format = '[ $symbol ($version) ](fg:green bg:surface2)'

[bun]
symbol = "🥟"
style = "bg:surface2"
format = '[ $symbol ($version) ](fg:rosewater bg:surface2)'

[java]
symbol = ""
style = "bg:surface2"
format = '[ $symbol ($version) ](fg:maroon bg:surface2)'

[dart]
symbol = ""
style = "bg:surface2"
format = '[ $symbol ($version) ](fg:sapphire bg:surface2)'

[docker_context]
symbol = " "
style = "bg:overlay0"
format = '[ $symbol $context ](fg:sky bg:overlay0)'
only_with_files = true

[kubernetes]
disabled = false
symbol = "⎈ "
style = "bg:overlay0"
format = '[ $symbol$context ](fg:sapphire bg:overlay0)'

[aws]
symbol = " "
style = "bg:overlay0"
format = '[ $symbol $profile ](fg:peach bg:overlay0)'

[gcloud]
symbol = " "
style = "bg:overlay0"
format = '[ $symbol $project ](fg:blue bg:overlay0)'

[fill]
symbol = " "

[cmd_duration]
min_time = 500
format = '[ 󱎫 $duration ](fg:subtext1)'

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold yellow)'
